---
title: "Exploratory Volatility Calculations"
author: "Holly Bossart"
date: "February 20, 2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(TTR)
library(tidyverse)


data = read.csv("Data/OHLCprices2.csv")
ticker = data.frame(unique(data$TICKER))
names(ticker)[1] <- "Company"


```

## 31 Companies
Data collected from WRDS CRSP Database.

```{r data}
data$COMNAM[data$COMNAM == 'WAL MART STORES INC'] <- 'WALMART INC'
comnames <- data.frame(unique(data$COMNAM))

```


## Breaking up individual data sets
```{r data}
oracle <- filter(data, data$COMNAM == 'ORACLE CORP')
microsoft <- filter(data, data$COMNAM == 'MICROSOFT CORP')
exxon <- filter(data, data$COMNAM == 'EXXON MOBIL CORP')
gm <- filter(data, data$COMNAM == 'GENERAL MOTORS CO')
ibm <- filter(data, data$COMNAM == 'INTERNATIONAL BUSINESS MACHS COR')
facebook <- filter(data, data$COMNAM == 'FACEBOOK INC')
chevron <- filter(data, data$COMNAM == 'CHEVRON CORP NEW')
apple <- filter(data, data$COMNAM == 'APPLE INC')
alibaba <- filter(data, data$COMNAM == 'ALIBABA GROUP HOLDING LTD')
pg <- filter(data, data$COMNAM == 'PROCTER & GAMBLE CO')
pfizer <- filter(data, data$COMNAM == 'PFIZER INC')
johnson <- filter(data, data$COMNAM == 'JOHNSON & JOHNSON')
disney <- filter(data, data$COMNAM == 'DISNEY WALT CO')
wellsfargo <- filter(data, data$COMNAM == 'WELLS FARGO & CO NEW')
jpmorgan <- filter(data, data$COMNAM == 'JPMORGAN CHASE & CO')
walmart <- filter(data, data$COMNAM == 'WALMART INC')
intel <- filter(data, data$COMNAM == 'INTEL CORP')
bankofa <- filter(data, data$COMNAM == 'BANK OF AMERICA CORP')
verizon <- filter(data, data$COMNAM == 'VERIZON COMMUNICATIONS INC')
att <- filter(data, data$COMNAM == 'A T & T INC')
homedep <- filter(data, data$COMNAM == 'HOME DEPOT INC')
citi <- filter(data, data$COMNAM == 'CITIGROUP INC')
amazon <- filter(data, data$COMNAM == 'AMAZON COM INC')
chinamob <- filter(data, data$COMNAM == 'CHINA MOBILE LTD')
taiwan <- filter(data, data$COMNAM == 'TAIWAN SEMICONDUCTOR MFG CO LTD')
novartis <- filter(data, data$COMNAM == 'NOVARTIS A G')
visa <- filter(data, data$COMNAM == 'VISA INC')
unhealth <- filter(data, data$COMNAM == 'UNITEDHEALTH GROUP INC')
busch <- filter(data, data$COMNAM == 'ANHEUSER BUSCH INBEV SA NV')
netflix <- filter(data, data$COMNAM == 'NETFLIX INC')


```

## Plotting Closing Price or Bid/Ask Average
### Oracle
```{r}
# making the data into time series plots
oracle.p.t <- ts(oracle$PRC, start = c(2015,1,1), frequency = 251.6)
summary(oracle.p.t)

```
```{r}
dev.new(width=12, height=6)
par(mfrow=c(1,1), mex=0.75)
plot.ts(oracle.p.t, ylim=c(30,75),xlab="2015-2019",main="Oracle Closing Prices 01/01/2015-12/31/2019")

```

### Microsoft
```{r}
microsoft.p.t <- ts(microsoft$PRC, start = c(2015,1,1), frequency = 251.6)
summary(microsoft.p.t)

```
```{r}
dev.new(width=12, height=6)
par(mfrow=c(1,1), mex=0.75)
plot.ts(microsoft.p.t, ylim=c(30,175),xlab="2015-2019",main="microsoft Closing Prices 01/01/2015-12/31/2019")

```
### exxon
```{r}
exxon.p.t <- ts(exxon$PRC, start = c(2015,1,1), frequency = 251.6)
summary(exxon.p.t)

```


